# Generated by Django 4.0.6 on 2022-07-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='arrival_time',
            new_name='time_of_arrival',
        ),
    ]
